NoteManager/Models/Note.cs
using System.ComponentModel.DataAnnotations;

namespace NoteManager.Models
{
    public class Note
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public string NoteText { get; set; }
        public DateTime CreatedDateTime { get; set; } = DateTime.Now;
    }
}

NoteManager/Controllers/NoteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NoteManager.Models;
using NoteManager.Repository.IRepository;
using System.Linq;

namespace NoteManager.Controllers
{
    public class NoteController : Controller
    {
        private readonly IWorkAction _workAction;

        public NoteController(IWorkAction workAction)
        {
            _workAction = workAction;
        }

        public IActionResult Index()
        {
            IEnumerable<Note> objNoteList = _workAction.Note.GetAll();
            return View(objNoteList);
        }

        public IActionResult Statistics()
        {
            IEnumerable<AddEditDeleteLog> objAddEditDeleteLogList = _workAction.AddEditDeleteLog.GetAll();
            var groups = objAddEditDeleteLogList.GroupBy(info => info.Flag)
                        .Select(group => new
                        {
                            Flag = group.Key,
                            Count = group.Count()
                        }).ToList();

            Dictionary<int,int> retvalues = new Dictionary<int,int>();
            foreach(var keyvalue in groups)
            {
                retvalues[keyvalue.Flag] = keyvalue.Count;
            }
            ViewBag.Flags = retvalues.Keys.ToList();
            ViewBag.Counts = retvalues.Values.ToList();
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Note obj)
        {
            if (ModelState.IsValid)
            {
                _workAction.Note.Add(obj);

                _workAction.AddEditDeleteLog.Add(new AddEditDeleteLog()
                {
                    NoteText = obj.NoteText,
                    Flag = 1,
                    ActionDateTime = DateTime.Now
                });
                _workAction.Save();

                TempData["success"] = "Note created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var noteFromDbFirst = _workAction.Note.GetFirstOrDefault(u => u.ID == id);

            if (noteFromDbFirst == null)
            {
                return NotFound();
            }
            return View(noteFromDbFirst);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Note obj)
        {
            if (ModelState.IsValid)
            {
                _workAction.Note.Update(obj);
                _workAction.AddEditDeleteLog.Add(new AddEditDeleteLog()
                {
                    NoteText = obj.NoteText,
                    Flag = 2,// later will replace with enum "Edit",
                    ActionDateTime = DateTime.Now
                }); ;
                _workAction.Save();
                TempData["success"] = "Note updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var noteFromDbFirst = _workAction.Note.GetFirstOrDefault(u => u.ID == id);

            if (noteFromDbFirst == null)
            {
                return NotFound();
            }

            return View(noteFromDbFirst);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _workAction.Note.GetFirstOrDefault(u => u.ID == id);
            if (obj == null)
            {
                return NotFound();
            }
            try
            {
                _workAction.Note.Remove(obj);
                _workAction.AddEditDeleteLog.Add(new AddEditDeleteLog()
                {
                    NoteText = obj.NoteText,
                    Flag = 3, //"Delete",
                    ActionDateTime = DateTime.Now
                });
                _workAction.Save();
            }
            catch (Exception ex)
            {
                TempData["success"] = "Note not Deleted " + ex.Message;
                return RedirectToAction("Index");
            }

            TempData["success"] = "Note deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

NoteManager/Views/Note/Create.cshtml
@model Note
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@if (SignInManager.IsSignedIn(User))
{

	<form method="post">
		<div class="border p-3 mt-4">
			<div class="row pb-2">
				<h2 class="text-primary">Create Note</h2>
				<hr />
			</div>
			<div class="mb-3">
				<label asp-for="NoteText"></label>
				<input asp-for="NoteText" multiple style="height:200px" class="form-control" />
				<span asp-validation-for="NoteText" class="text-danger"></span>
			</div>

			<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
			<a asp-controller="Note" asp-action="Index" class="btn btn-secondary" style="width:150px">
				Back to List
			</a>
		</div>
	</form>
}
@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

NoteManager/Views/Note/Delete.cshtml
@model Note
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@if (SignInManager.IsSignedIn(User))
{

	<form method="post" asp-action="Delete">
		<input asp-for="ID" hidden />
		<div class="border p-3 mt-4">
			<div class="row pb-2">
				<h2 class="text-primary">Delete Note</h2>
				<hr />
			</div>
			@*<div asp-validation-summary="All"></div>*@
			<div class="mb-3">
				<label asp-for="NoteText"></label>
				<input asp-for="NoteText" disabled style="height:200px" class="form-control" />
			</div>
			<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
			<a asp-controller="Note" asp-action="Index" class="btn btn-secondary" style="width:150px">
				Back to List
			</a>
		</div>
	</form>
}
@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

NoteManager/Views/Note/Edit.cshtml
@model Note
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@if (SignInManager.IsSignedIn(User))
{

	<form method="post" asp-action="Edit">
		<div class="border p-3 mt-4">
			<div class="row pb-2">
				<h2 class="text-primary">Edit Note</h2>
				<hr />
			</div>
			@*<div asp-validation-summary="All"></div>*@
			<div class="mb-3">
				<label asp-for="NoteText"></label>
				<input asp-for="NoteText" style="height:200px" class="form-control" />
				<span asp-validation-for="NoteText" class="text-danger"></span>
			</div>

			<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
			<a asp-controller="Note" asp-action="Index" class="btn btn-secondary" style="width:150px">
				Back to List
			</a>
		</div>
	</form>
}
@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

NoteManager/Views/Note/Index.cshtml
@model IEnumerable<Note>
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Index";
}

@if (SignInManager.IsSignedIn(User))
{
    <div class="container p-3">
        <div class="row pt-4">
            <div class="col-6">
                <h2 class="text-primary">Note List</h2>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Note" asp-action="Create" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> &nbsp; Create New Note
                </a>
            </div>
        </div>
        <br /><br />

        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Note Name
                    </th>
                    <th>
                        Note ID
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="50%">
                            @obj.NoteText
                        </td>
                        <td width="30%">
                            @obj.ID
                        </td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Note" asp-action="Edit" asp-route-id="@obj.ID"
                           class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                                <a asp-controller="Note" asp-action="Delete" asp-route-id="@obj.ID"
                           class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
}

NoteManager/Views/Note/Statistics.cshtml
@page
<div>
    <canvas id="myChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    var keys = [];
    var values = [];
</script>
@foreach (var key in ViewBag.Flags)
{  // need to be improved the below code
    <script>
        if (@key == 1) { keys.push("Create") }
        if (@key == 2) { keys.push("Edit") }
        if (@key == 3) { keys.push("Delete") }
    </script>
}
@foreach (var key in ViewBag.Counts)
{
    <script>values.push(@key)</script>
}
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@if (SignInManager.IsSignedIn(User))
{

    <script>
        const ctx = document.getElementById('myChart');

        new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [...keys],
                datasets: [{
                    label: 'Note Manager Statistics',
                    data: [...values],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }

                }
            }
        });
    </script>
    <div class="border p-3 mt-4">
    <a asp-controller="Note" asp-action="Index" class="btn btn-primary" style="width:150px">
        Back to List
    </a>
    </div>
}